all:
	clear
	gcc -o interpretador interpretador.c
	gcc -o escalonador escalonador.c
	gcc -o prog1 prog1.c
	gcc -o prog2 prog2.c
	gcc -o prog3 prog3.c
	gcc -o prog4 prog4.c
	gcc -o prog5 prog5.c
	./interpretador